---
output:
  html_document:
    keep_md: yes
params: 
    data: 
    purpose: "ok_art_sykdom"
    aar: "`r as.numeric(format(Sys.Date(), '%Y')) - 1`"
    selection_parameters: 
title: "`r paste('Kontroll av seleksjonsparameterne for:', params$purpose, paste(unique(c(min(params$aar), max(params$aar))),  collapse = ' - '))`"
---
```{r set_options, echo=FALSE, cache=FALSE, clean=FALSE}
linewidth <- getOption("width")
options(width = 1000)
```

```{r setup, include=FALSE}
# SET UP R ENVIRONMENT
# Attach packages
library(OKcheck)

# Import support data
# Translation table for PJS-codes
PJS_codes_2_text <- NVIpjsr::read_PJS_codes_2_text()

# Import variables input as parameter to the Rmd-file
data <- params$data
purpose <- params$purpose
aar <- params$aar
# selection_parameters should be a list built by NVIdb::set_disease_parameters or built similarly manually
selection_parameters <- params$selection_parameters
hensikt2select <- selection_parameters$hensikt2select
hensikt2delete <- selection_parameters$hensikt2delete
metode2select <- selection_parameters$metode2select
analytt2select <- selection_parameters$analytt2select
analytt2delete <- selection_parameters$analytt2delete
art2select <- selection_parameters$art2select

knitr::opts_chunk$set(echo=TRUE)
```

```{r, include = FALSE}
## Kontroll av seleksjonsparameterne for: `r purpose` `r paste(unique(c(min(aar), max(aar))), collapse = " - ")` per `r format(Sys.Date(), "%d.%m.%Y")`

```

<!-- Count hensiktkoder -->
```{r echo = FALSE}
# Heading and sub-heading for the table. Includes instructions for how to interpret the table
heading <- paste("<br/> <br/>",
                 "<h4> Tabell 1. Hensiktkoder registrert i data for", 
                 purpose, 
                 paste0(paste(unique(c(min(aar), max(aar))), collapse = " - "), ". </h4>"), 
                 "<h5> 'N obs' angir antall ganger koden er benyttet.",
                 "Hvis kolonnen 'Accepted' er inkludert,",
                 "betyr verdien 1 at koden er inkludert i seleksjons- eller eksklusjonsparametrene.",
                 "Dersom en kode merket 0 er spesifikk for den sykdommen/infeksjonen som det",
                 "selekteres for, bør den inkluderes i seleksjonsparametrene. </h5>")

# Counts the number of unique rows at sak-level in the dataset with hensiktkode
ktr <- OKcheck::count_PJScodes(PJSdata = PJSdata, 
                               variable = "hensiktkode", 
                               accepted = hensikt2select,
                               excluded = hensikt2delete,
                               translation_table = PJS_codes_2_text)

# Outputs the table if there are data in the table
OKcheck::knit_table_if_data(data = ktr, heading = heading)
```

<!-- Count metodekoder -->
```{r echo = FALSE}
# Heading and sub-heading for the table. Includes instructions for how to interpret the table
heading <- paste("<br/> <br/>",
                 "<h4> Tabell 2. Metodekoder registrert i data for",  
                 purpose, 
                 paste0(paste(unique(c(min(aar), max(aar))), collapse = " - "), ". </h4>"), 
                 "<h5> 'N obs' angir antall ganger koden er benyttet.",
                 "Hvis kolonnen 'Accepted' er inkludert,",
                 "betyr verdien 1 at koden er inkludert i seleksjonsparametrene.",
                 "Dersom en kode merket 0 er spesifikk for den sykdommen/infeksjonen som det",
                 "selekteres for, bør den inkluderes i seleksjonsparametrene. </h5>")

# Counts the number of unique rows at metode-level in the dataset with metodekode
ktr <- OKcheck::count_PJScodes(PJSdata = PJSdata, 
                               variable = "metodekode", 
                               accepted = metode2select,
                               translation_table = PJS_codes_2_text)

# Outputs the table if there are data in the table
OKcheck::knit_table_if_data(data = ktr, heading = heading)
```

<!-- Count konklusjonsanalyttkoder -->
```{r echo = FALSE}
# Heading and sub-heading for the table. Includes instructions for how to interpret the table
heading <- paste("<br/> <br/>",
                 "<h4> Tabell 3. Konklusjonsanalyttkoder registrert i data for",  
                 purpose, 
                 paste0(paste(unique(c(min(aar), max(aar))), collapse = " - "), ". </h4>"), 
                 "<h5> 'N obs' angir antall ganger koden er benyttet.",
                 "Hvis kolonnen 'Accepted' er inkludert,",
                 "betyr verdien 1 at koden er inkludert i seleksjons- eller eksklusjonsparametrene.",
                 "Dersom en kode merket 0 er spesifikk for den sykdommen/infeksjonen som det",
                 "selekteres for, bør den inkluderes i seleksjonsparametrene. </h5>")

# Counts the number of unique rows at prove-konklusjon-level in the dataset with konklusjonsanalyttkode
ktr <- OKcheck::count_PJScodes(PJSdata = PJSdata,
                               variable = "konkl_analyttkode",
                               accepted = analytt2select, 
                               excluded = analytt2delete,
                               translation_table = PJS_codes_2_text)

# Outputs the table if there are data in the table
OKcheck::knit_table_if_data(data = ktr, heading = heading)

```

<!-- Count artkoder -->
```{r echo = FALSE}
# Heading and sub-heading for the table. Includes instructions for how to interpret the table
heading <- paste("<br/> <br/>",
                 "<h4> Tabell 4. Artskoder registrert i data for",  
                 purpose, 
                 paste0(paste(unique(c(min(aar), max(aar))), collapse = " - "), ". </h4>"), 
                 "<h5> 'N obs' angir antall ganger koden er benyttet.",
                 "Hvis kolonnen 'Accepted' er inkludert,",
                 "betyr verdien 1 at koden er inkludert i seleksjonsparametrene.",
                 "Dersom en kode merket 0 er spesifikk for den sykdommen/infeksjonen som det",
                 "selekteres for, bør den inkluderes i seleksjonsparametrene. </h5>")

# Removes breed from artkode
PJSdata <- PJSdata  |> 
  NVIpjsr::add_PJS_code_description(PJS_variable_type = "auto",
                                    code_colname = "artkode",
                                    new_column = "auto",
                                    position = "last") |> 
  NVIpjsr::add_PJS_code_description(PJS_variable_type = "artrase",
                                    code_colname = "art",
                                    new_column = "artkode",
                                    backward = TRUE,
                                    position = "last",
                                    overwrite = TRUE)

# Counts the number of unique rows at prove-level in the dataset with artkode
ktr <- OKcheck::count_PJScodes(PJSdata = PJSdata,
                               variable = "artkode",
                               accepted = art2select,
                               translation_table = PJS_codes_2_text)

# Outputs the table if there are data in the table
OKcheck::knit_table_if_data(data = ktr, heading = heading)

```

```{r set-options, echo=FALSE, cache=FALSE, clean=FALSE}
options(width = unlist(linewidth))
```


