---
output:
  html_document:
    theme: sandstone
params: 
    set_title: !r paste("Kontroll av PJS-data for:", purpose, aar)
title: "`r params$set_title`"
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 1000)
```

```{r setup, include=FALSE}

# Attach packages
library(NVIbatch)
use_pkg(pkg = c("dplyr", "tidyr", "knitr", "kableExtra"))
use_NVIverse(pkg = c("NVIdb", "NVIpjsr", "OKcheck"))

# Global variables
# For use in filenames
today <- format(Sys.Date(), "%Y%m%d")

# Import support data
# Translation table for PJS-codes
PJS_codes_2_text <- NVIpjsr::read_PJS_codes_2_text()

# Table with accepted code combinations per OK-program (purpose)
accepted_codes <- openxlsx::read.xlsx(xlsxFile = paste0(NVIdb::set_dir_NVI("OKprogrammer"),
                                                        "OKstatistikkApp/Stottedata/Kontrolltabeller_PJS_", 
                                                        aar, 
                                                        ".xlsx"),
                                      detectDates = TRUE)

accepted_codes <- subset(accepted_codes, accepted_codes$program == purpose)

knitr::opts_chunk$set(echo=TRUE)
```

```{r, include = FALSE}
## Kontroll av PJS-data for: `r purpose` `r aar` per `r format(Sys.Date(), "%d.%m.%Y")`

```

<!-- Tabell I-1. Saker som ikke er avsluttet -->
```{r child=system.file('templates', "check_avsluttet.Rmd", package = "OKcheck")}
```
<!-- Check code combinations -->
```{r echo = FALSE}
# All combinations of variables that should be checked
variable_names <- c("ansvarlig_seksjon", "utf_seksjon", 
                        "hensiktkode", "rekvirenttype", "eier_lokalitettype", "annen_aktortype",
                        "artkode", "driftsformkode", "oppstallingkode", "fysiologisk_stadiumkode", "kjonn",
                        "provetypekode", "provematerialekode", "forbehandlingkode",
                        "metodekode", 
                        "konkl_typekode", "konkl_kjennelsekode", "konkl_analyttkode", 
                        "res_kjennelsekode", "res_analyttkode")

combinations <- unique(accepted_codes[, c("var1", "var2", "var3")])
combinations <- subset(combinations, 
                       combinations$var1 %in% variable_names &
                         (is.na(combinations$var2) | combinations$var2 %in% variable_names) &
                         (is.na(combinations$var3) | combinations$var3 %in% variable_names))

# Make a table with fixed number of rows, thereby a for loop can be avoided
combinations <- rbind(combinations,
                      as.data.frame(matrix(nrow = 10 - dim(combinations)[1], 
                                           ncol = 3, 
                                           dimnames = list(NULL, c("var1", "var2", "var3")))))

# # Relation between column name and pJS-type as used by NVIdb::add_PJS_code_description below 
# PJS_code_variables <- c("hensiktkode", "rekvirenttype", "eier_lokalitettype", "annen_aktortype",
#                         "artkode", "driftsformkode", "oppstallingkode", "fysiologisk_stadiumkode", "kjonn",
#                         "provetypekode", "provematerialekode", "forbehandlingkode",
#                         "utf_seksjon",
#                         "metodekode",
#                         "konkl_typekode", "konkl_kjennelsekode", "konkl_analyttkode",
#                         "res_kjennelsekode", "res_analyttkode")

# Prepare for first call to child
# Find code combination
code_variable <- as.vector(t(combinations[1,]))
code_variable <- subset(code_variable, !is.na(code_variable))
```
<!-- Check first code combination -->
```{r child=system.file('templates', "check_code_combination.Rmd", package = "OKcheck")}
```

<!-- Check code combinations -->
```{r echo = FALSE}
# Find code combination
code_variable <- as.vector(t(combinations[2,]))
code_variable <- subset(code_variable, !is.na(code_variable))
```
<!-- Check second code combination -->
```{r child=system.file('templates', "check_code_combination.Rmd", package = "OKcheck")}
```

<!-- Check code combinations -->
```{r echo = FALSE}
# Find code combination
code_variable <- as.vector(t(combinations[3,]))
code_variable <- subset(code_variable, !is.na(code_variable))
```
<!-- Check second code combination -->
```{r child=system.file('templates', "check_code_combination.Rmd", package = "OKcheck")}
```

<!-- Check code combinations -->
```{r echo = FALSE}
# Find code combination
code_variable <- as.vector(t(combinations[4,]))
code_variable <- subset(code_variable, !is.na(code_variable))
```
<!-- Check second code combination -->
```{r child=system.file('templates', "check_code_combination.Rmd", package = "OKcheck")}
```

<!-- Check code combinations -->
```{r echo = FALSE}
# Find code combination
code_variable <- as.vector(t(combinations[5,]))
code_variable <- subset(code_variable, !is.na(code_variable))
```
<!-- Check second code combination -->
```{r child=system.file('templates', "check_code_combination.Rmd", package = "OKcheck")}
```

<!-- Check code combinations -->
```{r echo = FALSE}
# Find code combination
code_variable <- as.vector(t(combinations[6,]))
code_variable <- subset(code_variable, !is.na(code_variable))
```
<!-- Check second code combination -->
```{r child=system.file('templates', "check_code_combination.Rmd", package = "OKcheck")}
```

<!-- Check code combinations -->
```{r echo = FALSE}
# Find code combination
code_variable <- as.vector(t(combinations[7,]))
code_variable <- subset(code_variable, !is.na(code_variable))
```
<!-- Check second code combination -->
```{r child=system.file('templates', "check_code_combination.Rmd", package = "OKcheck")}
```

<!-- Check code combinations -->
```{r echo = FALSE}
# Find code combination
code_variable <- as.vector(t(combinations[8,]))
code_variable <- subset(code_variable, !is.na(code_variable))
```
<!-- Check second code combination -->
```{r child=system.file('templates', "check_code_combination.Rmd", package = "OKcheck")}
```

<!-- Check code combinations -->
```{r echo = FALSE}
# Find code combination
code_variable <- as.vector(t(combinations[9,]))
code_variable <- subset(code_variable, !is.na(code_variable))
```
<!-- Check second code combination -->
```{r child=system.file('templates', "check_code_combination.Rmd", package = "OKcheck")}
```

<!-- Check code combinations -->
```{r echo = FALSE}
# Find code combination
code_variable <- as.vector(t(combinations[10,]))
code_variable <- subset(code_variable, !is.na(code_variable))
```
<!-- Check second code combination -->
```{r child=system.file('templates', "check_code_combination.Rmd", package = "OKcheck")}
```

<!-- Tabell K-4. Prover med mer enn en provekonklusjon for identiske proveanalytter -->
```{r child=system.file('templates', "check_doubble_prv_konkl.Rmd", package = "OKcheck")}
```

<!-- Tabell K-5. Prover med forelopig konklusjon -->
```{r child=system.file('templates', "check_forelopig_konkl.Rmd", package = "OKcheck")}
```

